/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDay: typeof import('./components/TheDay/TheDay.vue')['default']
    TheDayItem: typeof import('./components/TheDay/TheDayItem.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheRange: typeof import('./components/TheRange/TheRange.vue')['default']
    TheRangeProgress: typeof import('./components/TheRange/TheRangeProgress.vue')['default']
    TheRangeThumb: typeof import('./components/TheRange/TheRangeThumb.vue')['default']
    TheTheme: typeof import('./components/TheTheme.vue')['default']
  }
}
